version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nomelette-api"
s3_bucket = "nomelette-api-deployment"
s3_prefix = "nomelette-api"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
