service: nomelette-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-1

functions:
  recipes:
    handler: api/recipes/get.handler
    events:
      - http: GET recipes/{recipeId}
  streamEvent:
    handler: api/streamEvent/index.handler
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          arn:
            Fn::GetAtt:
              - NomeletteTable
              - StreamArn

# To keep deployments to an absolute minimum, exclude all superflous files
package:
  exclude:
    - .DS_Store
    - tests/**
    - .dynamodb/**
    - node_modules/**

resources:
  Resources:
    NomeletteTable:
      Type: AWS::DynamoDB::Table
      #DeletionPolicy: Retain
      Properties:
        TableName: nomelette.co.uk

        # Streams: For indexing and post-processing
        StreamSpecification:
          StreamViewType: NEW_IMAGE

        # PK/SK Definitions / schemas
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE

        # Provisioning
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    start:
      migrate: true
    stages:
      - dev

plugins:
  - serverless-dynamodb-local
  - serverless-offline #serverless-offline needs to be last in the list

